<?php

return [

    // OPERASIONAL & MANAJEMEN (5 modul)

    [
        'slug'              => 'membuat-sop-kuat-konsisten-umkm',
        'judul'             => 'Membuat SOP yang Kuat & Konsisten bagi UMKM',
        'kategori'          => 'Operasional',
        'tingkat'           => 'Menengah',
        'durasi'            => '9 menit',
        'creator'           => 'Foodizz Channel',
        'youtube_id'        => 'BuM9G-7OF2c',
        'thumbnail'         => 'https://img.youtube.com/vi/BuM9G-7OF2c/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=BuM9G-7OF2c',
        'deskripsi'         => 'Panduan praktis membuat Standard Operating Procedure (SOP) yang efektif untuk UMKM. Pelajari cara menyusun prosedur kerja agar bisnis berjalan konsisten meski tanpa pengawasan langsung pemilik.',
        'tags'              => ['sop', 'operasional', 'manajemen', 'prosedur', 'konsistensi'],
        'transcript_source' => 'curated_outline',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Pembukaan — Mengapa bisnis ramai sering berantakan tanpa SOP.'],
            ['time' => '01:30', 'text' => 'Apa itu SOP — Definisi dan fungsi Standar Operasional Prosedur.'],
            ['time' => '03:00', 'text' => 'Manfaat SOP — Konsistensi layanan dan pengurangan kesalahan operasional.'],
            ['time' => '04:30', 'text' => 'Cara Membuat SOP Sederhana — Langkah-langkah praktis untuk UMKM.'],
            ['time' => '06:30', 'text' => 'Implementasi SOP di Tim — Cara mensosialisasikan ke karyawan.'],
            ['time' => '08:00', 'text' => 'Evaluasi & Perbaikan SOP — Kapan SOP perlu diperbarui.'],
        ],
    ],

    [
        'slug'              => 'mengelola-bisnis-secara-efisien',
        'judul'             => 'Mengelola Bisnis Secara Efisien — Mulai dari Sini!',
        'kategori'          => 'Operasional',
        'tingkat'           => 'Pemula',
        'durasi'            => '16 menit',
        'creator'           => 'dr. Tirta (#Suaratirta)',
        'youtube_id'        => 'TlzWi5O_ySg',
        'thumbnail'         => 'https://img.youtube.com/vi/TlzWi5O_ySg/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=TlzWi5O_ySg',
        'deskripsi'         => 'dr. Tirta membahas prinsip-prinsip dasar mengelola bisnis dengan efisien. Cocok untuk pemilik UMKM yang ingin meningkatkan produktivitas tanpa menambah biaya operasional.',
        'tags'              => ['efisiensi', 'manajemen', 'operasional', 'produktivitas'],
        'transcript_source' => 'curated_outline',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Pembukaan — Mengapa efisiensi operasional adalah kunci keberlangsungan UMKM.'],
            ['time' => '02:00', 'text' => 'Mindset Efisiensi — Cara berpikir pemilik bisnis yang produktif.'],
            ['time' => '04:30', 'text' => 'Identifikasi Pemborosan — Cara menemukan proses yang tidak efisien.'],
            ['time' => '07:30', 'text' => 'Mengelola Tim Kerja — Tips mengatur jadwal dan tugas karyawan.'],
            ['time' => '10:30', 'text' => 'Sistem Operasional Sederhana — Cara membangun sistem kerja konsisten.'],
            ['time' => '13:30', 'text' => 'Studi Kasus — Contoh efisiensi yang berhasil diterapkan.'],
            ['time' => '15:00', 'text' => 'Penutup — Langkah pertama meningkatkan efisiensi mulai hari ini.'],
        ],
    ],

    // ── CHAPTER RESMI dari Kelly Patricia ──
    [
        'slug'              => '10-kesalahan-bisnis-cara-hindarinya',
        'judul'             => '10 Kesalahan Bisnis (dan Cara Menghindarinya)',
        'kategori'          => 'Operasional',
        'tingkat'           => 'Pemula',
        'durasi'            => '11 menit',
        'creator'           => 'Kelly Patricia',
        'youtube_id'        => 'Gqb5PLWH6K4',
        'thumbnail'         => 'https://img.youtube.com/vi/Gqb5PLWH6K4/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=Gqb5PLWH6K4',
        'deskripsi'         => 'Identifikasi 10 kesalahan paling umum yang dilakukan pelaku UMKM pemula dan strategi praktis untuk menghindarinya. Mencakup keuangan, manajemen stok, harga jual, dan sistem bisnis.',
        'tags'              => ['kesalahan-bisnis', 'tips', 'manajemen', 'pelajaran'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Intro — 10 kesalahan pebisnis pemula yang harus dihindari.'],
            ['time' => '00:40', 'text' => 'Campur Uang Bisnis & Pribadi — Kesalahan fatal yang sering terjadi.'],
            ['time' => '01:47', 'text' => 'Ga Catat Keuangan — Akibat tidak punya pencatatan transaksi.'],
            ['time' => '02:40', 'text' => 'Asal Pasang Harga — Cara menentukan harga yang tepat.'],
            ['time' => '04:20', 'text' => 'Stok Kebanyakan — Risiko terlalu banyak inventaris.'],
            ['time' => '05:13', 'text' => 'Fokus Jualan, Lupa Atur Duit — Pentingnya mengelola arus kas.'],
            ['time' => '06:34', 'text' => 'Jualan ke "Semua Orang" — Mengapa target market harus spesifik.'],
            ['time' => '07:15', 'text' => 'Semua Sendiri — Kapan harus mulai delegasi.'],
            ['time' => '07:58', 'text' => 'Ga Bikin Sistem & SOP — Mengapa sistem penting untuk scaling.'],
            ['time' => '08:58', 'text' => 'Ga Siapin Dana Darurat — Pentingnya emergency fund untuk bisnis.'],
            ['time' => '10:00', 'text' => 'Terlalu Boros Diawal — Cara menjaga budget di tahap awal.'],
        ],
    ],

    // ── CHAPTER RESMI dari Raymond Chin ──
    [
        'slug'              => 'kenapa-bisnis-umkm-gagal',
        'judul'             => 'Kenapa Mayoritas Bisnis UMKM Kalian Gagal?',
        'kategori'          => 'Operasional',
        'tingkat'           => 'Menengah',
        'durasi'            => '9 menit',
        'creator'           => 'Raymond Chin',
        'youtube_id'        => 'hXOCjdtKiks',
        'thumbnail'         => 'https://img.youtube.com/vi/hXOCjdtKiks/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=hXOCjdtKiks',
        'deskripsi'         => 'Raymond Chin membongkar 3 alasan utama kenapa banyak UMKM di Indonesia gagal bertahan. Mencakup digitalisasi, persaingan dengan perusahaan besar, dan kesulitan mengikuti tren.',
        'tags'              => ['kegagalan-umkm', 'teknologi', 'digital', 'adaptasi'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Alasan Bisnis UMKM Gagal — Pembukaan tentang realita UMKM Indonesia.'],
            ['time' => '00:36', 'text' => 'Chapter 1: Lack of Digitalization — Kurangnya adopsi teknologi.'],
            ['time' => '04:03', 'text' => 'Chapter 2: Competition From Larger Firms — Bersaing dengan perusahaan besar.'],
            ['time' => '06:58', 'text' => 'Chapter 3: Difficulty on Catching Trends — Kesulitan mengikuti tren pasar.'],
            ['time' => '08:44', 'text' => 'Conclusion — Kesimpulan dan langkah praktis untuk UMKM.'],
        ],
    ],

    // ── CHAPTER RESMI dari Raymond Chin x Hermanto Tanoko ──
    [
        'slug'              => 'strategi-mindset-bisnis-hermanto-tanoko',
        'judul'             => 'Strategi & Mindset Bisnis Orang Terkaya ke-7 Indonesia',
        'kategori'          => 'Operasional',
        'tingkat'           => 'Lanjutan',
        'durasi'            => '39 menit',
        'creator'           => 'Raymond Chin ft. Hermanto Tanoko',
        'youtube_id'        => 'hrfJprWnvEo',
        'thumbnail'         => 'https://img.youtube.com/vi/hrfJprWnvEo/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=hrfJprWnvEo',
        'deskripsi'         => 'Wawancara mendalam dengan Hermanto Tanoko (orang terkaya ke-7 Indonesia, Forbes) tentang strategi membangun bisnis jangka panjang, mindset entrepreneur, dan cara menghadapi tantangan usaha.',
        'tags'              => ['mindset', 'strategi', 'jangka-panjang', 'leadership'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Forbes 10th Richest in Indonesia — Pengenalan Hermanto Tanoko.'],
            ['time' => '01:00', 'text' => 'Kalau ga punya privilege, ga mungkin bisnis! — Mitos tentang modal awal.'],
            ['time' => '04:19', 'text' => 'Apakah "passion" beneran ada — Diskusi tentang passion dalam bisnis.'],
            ['time' => '08:53', 'text' => 'What makes a good business — Ciri bisnis yang baik.'],
            ['time' => '12:05', 'text' => 'Keputusan terbaik selama hidup — Decision making yang membentuk karir.'],
            ['time' => '16:20', 'text' => 'Krisis selalu tumbuh lebih cepat — Pelajaran dari masa krisis.'],
            ['time' => '17:24', 'text' => 'Keputusan terburuk selama hidup — Belajar dari kegagalan.'],
            ['time' => '20:03', 'text' => 'Rahasia bikin perusahaan besar — Strategi membangun bisnis skala besar.'],
            ['time' => '25:30', 'text' => 'Karakter vs skill — Mana yang lebih penting?'],
            ['time' => '29:25', 'text' => 'Seberapa penting pasangan hidup — Peran support system.'],
            ['time' => '31:53', 'text' => 'HAL PALING PENTING UNTUK SUKSES — Inti dari kesuksesan bisnis.'],
            ['time' => '36:26', 'text' => 'Umur 27 ngapain? — Nasihat untuk anak muda.'],
            ['time' => '38:34', 'text' => 'Closing — Penutup dan key takeaways.'],
        ],
    ],

    // PEMASARAN (3 modul)

    [
        'slug'              => 'strategi-pemasaran-7p-umkm',
        'judul'             => 'Strategi Pemasaran 7P untuk UMKM',
        'kategori'          => 'Pemasaran',
        'tingkat'           => 'Menengah',
        'durasi'            => '14 menit',
        'creator'           => 'Marketeers TV',
        'youtube_id'        => 'DurWKcKgaE4',
        'thumbnail'         => 'https://img.youtube.com/vi/DurWKcKgaE4/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=DurWKcKgaE4',
        'deskripsi'         => 'Penerapan kerangka 7P (Product, Price, Place, Promotion, People, Process, Physical Evidence) untuk UMKM. Strategi pemasaran komprehensif berbasis teori marketing modern, dibawakan oleh Ignatius Untung.',
        'tags'              => ['marketing-mix', '7p', 'strategi-pemasaran', 'teori-marketing'],
        'transcript_source' => 'curated_outline',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Pembukaan — Pengenalan konsep marketing mix 7P.'],
            ['time' => '02:00', 'text' => 'Product & Price — Menentukan produk dan strategi harga.'],
            ['time' => '05:00', 'text' => 'Place & Promotion — Saluran distribusi dan strategi promosi.'],
            ['time' => '08:00', 'text' => 'People, Process & Physical Evidence — SDM, standar layanan, bukti fisik.'],
            ['time' => '11:00', 'text' => 'Implementasi 7P untuk UMKM — Contoh penerapan nyata.'],
            ['time' => '13:00', 'text' => 'Penutup — Tips memulai dengan kerangka 7P.'],
        ],
    ],

    // ── CHAPTER RESMI dari Aris Prayitno ──
    [
        'slug'              => 'digital-marketing-pemula-umkm',
        'judul'             => 'Jualan Laris — Praktek Digital Marketing untuk Pemula UMKM',
        'kategori'          => 'Pemasaran',
        'tingkat'           => 'Pemula',
        'durasi'            => '21 menit',
        'creator'           => 'Aris Prayitno',
        'youtube_id'        => 'uznkmpmmYA8',
        'thumbnail'         => 'https://img.youtube.com/vi/uznkmpmmYA8/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=uznkmpmmYA8',
        'deskripsi'         => 'Tutorial praktis digital marketing untuk pemilik UMKM yang baru mulai online. Fokus pada pemanfaatan Google Maps sebagai strategi digital marketing gratis untuk bisnis offline & online.',
        'tags'              => ['digital-marketing', 'pemula', 'google-maps', 'jualan-online'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Intro — Belajar dan langsung Praktek Digital Marketing.'],
            ['time' => '01:50', 'text' => 'Apa itu Digital Marketing — Pengenalan konsep dasar.'],
            ['time' => '03:26', 'text' => 'Mengapa Google Maps — Alasan Google Maps sebagai tools awal.'],
            ['time' => '05:31', 'text' => 'Pengetahuan Umum Tentang Google Maps — Cara kerja platform.'],
            ['time' => '10:45', 'text' => 'Menambahkan Lokasi di Google Maps — Tutorial praktis step-by-step.'],
            ['time' => '15:27', 'text' => 'Menambahkan Website atau Instagram di Google Maps — Integrasi social media.'],
            ['time' => '19:24', 'text' => 'Kesimpulan — Tips memulai digital marketing dari Google Maps.'],
        ],
    ],

    [
        'slug'              => 'strategi-pemasaran-lokal-umkm',
        'judul'             => '10 Strategi Pemasaran Lokal untuk UMKM Baru',
        'kategori'          => 'Pemasaran',
        'tingkat'           => 'Pemula',
        'durasi'            => '29 menit',
        'creator'           => 'Jejolok',
        'youtube_id'        => '0FaIsorPVgA',
        'thumbnail'         => 'https://img.youtube.com/vi/0FaIsorPVgA/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=0FaIsorPVgA',
        'deskripsi'         => '10 strategi pemasaran lokal yang efektif untuk UMKM yang baru berjalan. Mulai dari pendekatan digital seperti Google Bisnisku hingga kerja sama dengan komunitas lokal. Cocok untuk pelaku UMKM dengan budget terbatas.',
        'tags'              => ['pemasaran-lokal', 'brand-awareness', 'jangkauan-pasar', 'budget-rendah'],
        'transcript_source' => 'curated_outline',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Pembukaan — Mengapa pemasaran lokal penting untuk UMKM baru.'],
            ['time' => '02:30', 'text' => 'Strategi #1-2 — Brand awareness lokal dan signage strategis.'],
            ['time' => '06:30', 'text' => 'Strategi #3-4 — Networking dan kerjasama dengan UMKM tetangga.'],
            ['time' => '11:00', 'text' => 'Strategi #5-6 — Memanfaatkan komunitas dan acara lokal.'],
            ['time' => '15:30', 'text' => 'Strategi #7-8 — Event marketing dan partisipasi komunitas.'],
            ['time' => '20:00', 'text' => 'Strategi #9-10 — Program loyalitas dan referral pelanggan.'],
            ['time' => '24:00', 'text' => 'Implementasi — Cara prioritaskan strategi sesuai bisnis Anda.'],
            ['time' => '27:00', 'text' => 'Penutup — Tips eksekusi dengan budget terbatas.'],
        ],
    ],

    // KEUANGAN (2 modul) — KEDUANYA punya chapter resmi
    // ── CHAPTER RESMI dari Kelly Patricia ──
    [
        'slug'              => 'cara-kelola-uang-usaha-kecil',
        'judul'             => 'Cara Kelola Uang untuk Usaha Kecil (Mulai dari Sini)',
        'kategori'          => 'Keuangan',
        'tingkat'           => 'Pemula',
        'durasi'            => '10 menit',
        'creator'           => 'Kelly Patricia',
        'youtube_id'        => 'rHvTj2shiuw',
        'thumbnail'         => 'https://img.youtube.com/vi/rHvTj2shiuw/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=rHvTj2shiuw',
        'deskripsi'         => '4 Langkah praktis mengelola keuangan usaha kecil: money management, pencatatan, laporan, dan keputusan keuangan. Penjelasan ringkas untuk pemilik UMKM.',
        'tags'              => ['cash-flow', 'keuangan-dasar', 'pencatatan', 'laporan-keuangan'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Usaha Kecil HARUS BISA Kelola Duit — Pembukaan dan urgensinya.'],
            ['time' => '02:01', 'text' => 'Money Management — Prinsip dasar mengelola uang bisnis.'],
            ['time' => '04:57', 'text' => 'Pencatatan Keuangan — Cara catat pemasukan dan pengeluaran.'],
            ['time' => '07:27', 'text' => 'Laporan Keuangan — Membuat laporan sederhana untuk UMKM.'],
            ['time' => '09:05', 'text' => 'Keputusan Keuangan — Cara ambil keputusan berdasarkan data finansial.'],
        ],
    ],

    // ── CHAPTER RESMI dari Kelly Patricia ──
    [
        'slug'              => 'ngerti-keuangan-bisnis-10-menit',
        'judul'             => 'Mengerti Keuangan Bisnis dalam 10 Menit (untuk Pemula)',
        'kategori'          => 'Keuangan',
        'tingkat'           => 'Pemula',
        'durasi'            => '7 menit',
        'creator'           => 'Kelly Patricia',
        'youtube_id'        => '6DHoIp5uTIo',
        'thumbnail'         => 'https://img.youtube.com/vi/6DHoIp5uTIo/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=6DHoIp5uTIo',
        'deskripsi'         => 'Konsep dasar keuangan bisnis dijelaskan ringkas dengan contoh cerita Bisnis Kaos Lisa. Membahas Income Statement, Balance Sheet, dan hubungan keduanya.',
        'tags'              => ['literasi-keuangan', 'income-statement', 'balance-sheet', 'profit'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Apa itu Keuangan Bisnis — Pembukaan dan kenapa harus paham.'],
            ['time' => '01:00', 'text' => 'Cerita: Bisnis Kaos Lisa — Studi kasus untuk memahami konsep.'],
            ['time' => '02:36', 'text' => 'Income Statement — Memahami laporan laba rugi.'],
            ['time' => '04:51', 'text' => 'Balance Sheet — Memahami neraca keuangan.'],
            ['time' => '06:34', 'text' => 'Hubungan antara 2 Laporan — Bagaimana laporan saling terkait.'],
        ],
    ],

    // SDM (2 modul) — KEDUANYA punya chapter resmi
    // ── CHAPTER RESMI dari Tanya Kak Sam ──
    [
        'slug'              => 'tips-merekrut-karyawan-pertama-umkm',
        'judul'             => 'Tips Merekrut Karyawan Pertama untuk UMKM',
        'kategori'          => 'SDM',
        'tingkat'           => 'Menengah',
        'durasi'            => '49 menit',
        'creator'           => 'Tanya Kak Sam',
        'youtube_id'        => 'VG0hyi_FROA',
        'thumbnail'         => 'https://img.youtube.com/vi/VG0hyi_FROA/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=VG0hyi_FROA',
        'deskripsi'         => 'Podcast Kak Sam bersama Dewi Meisari (CEO ukmindonesia.id) tentang masalah UMKM saat merekrut karyawan, proses kurasi, ketakutan UMI, dan ekspektasi hiring pertama kali.',
        'tags'              => ['rekrutmen', 'karyawan', 'sdm', 'podcast', 'hr'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Introduction — Pembukaan podcast dengan Dewi Meisari.'],
            ['time' => '02:08', 'text' => 'Pengalaman Dewi Meisari — Mengkurasi UMKM Indonesia.'],
            ['time' => '09:35', 'text' => 'Proses Merekrut Orang — Tahapan rekrutmen untuk UMKM.'],
            ['time' => '15:47', 'text' => 'Salah Satu Ketakutan UMI — Hambatan psikologis saat hiring.'],
            ['time' => '28:56', 'text' => 'Ekspektasi Hiring Orang Pertama Kali — Realita vs ekspektasi.'],
            ['time' => '41:51', 'text' => 'Catatan untuk UKM yang Mau Naik Kelas — Strategi scaling.'],
            ['time' => '48:12', 'text' => 'Pesan Kak Sam — Closing dari Samuel Amarta.'],
            ['time' => '48:40', 'text' => 'Pesan Dewi Meisari — Closing dari Dewi Meisari.'],
        ],
    ],

    // ── CHAPTER RESMI dari Kelly Patricia ──
    [
        'slug'              => 'cara-hitung-gaji-karyawan',
        'judul'             => 'Cara Hitung Gaji Karyawan (Pemilik Usaha Harus Tahu!)',
        'kategori'          => 'SDM',
        'tingkat'           => 'Menengah',
        'durasi'            => '9 menit',
        'creator'           => 'Kelly Patricia',
        'youtube_id'        => 'UP0GqDJ562g',
        'thumbnail'         => 'https://img.youtube.com/vi/UP0GqDJ562g/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=UP0GqDJ562g',
        'deskripsi'         => 'Cara termudah hitung budget gaji untuk rekrut tim pintar tanpa takut rugi, meskipun budget pas-pasan. Termasuk tips rekrut freelance.',
        'tags'              => ['gaji', 'budget', 'sdm', 'freelance', 'rekrutmen'],
        'transcript_source' => 'official_chapter',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Intro — Pembukaan tentang hitung gaji karyawan.'],
            ['time' => '00:56', 'text' => '#1 Kapan Siap Rekrut Karyawan — Indikator waktu tepat hiring.'],
            ['time' => '02:48', 'text' => '#2 Cara Hitung Budget Gaji — Rumus dan tools praktis.'],
            ['time' => '05:57', 'text' => '#3 Kalau Budget Ga Cukup — Solusi untuk budget terbatas.'],
            ['time' => '08:04', 'text' => '#4 Tips Rekrut Freelance — Alternatif fleksibel untuk UMKM.'],
        ],
    ],

    // TEKNOLOGI (1 modul)

    [
        'slug'              => 'infrastruktur-digital-umkm-cnbc',
        'judul'             => 'Jurus Perkuat Modal & Infrastruktur Digital bagi Bisnis UMKM',
        'kategori'          => 'Teknologi',
        'tingkat'           => 'Menengah',
        'durasi'            => '20 menit',
        'creator'           => 'CNBC Indonesia',
        'youtube_id'        => 'uz6lyzZG7Yg',
        'thumbnail'         => 'https://img.youtube.com/vi/uz6lyzZG7Yg/hqdefault.jpg',
        'url'               => 'https://www.youtube.com/watch?v=uz6lyzZG7Yg',
        'deskripsi'         => 'Dialog CNBC Indonesia bersama Andi Taufan Garuda Putra (Founder & CEO Amartha) tentang inklusi keuangan UMKM, akses permodalan, dan infrastruktur digital bisnis online-to-offline.',
        'tags'              => ['infrastruktur-digital', 'teknologi', 'modal', 'inklusi-keuangan', 'amartha'],
        'transcript_source' => 'curated_outline',
        'transcript'        => [
            ['time' => '00:00', 'text' => 'Pembukaan — CNBC Indonesia membuka diskusi UMKM digital.'],
            ['time' => '02:30', 'text' => 'Pentingnya Digitalisasi — Mengapa UMKM wajib go digital sekarang.'],
            ['time' => '06:00', 'text' => 'Akses Permodalan — Sumber modal untuk UMKM di era digital.'],
            ['time' => '10:00', 'text' => 'Infrastruktur Digital — Tools dan platform yang dibutuhkan.'],
            ['time' => '13:30', 'text' => 'Inklusi Keuangan — Mendorong UMKM masuk ke ekosistem digital.'],
            ['time' => '16:30', 'text' => 'Tantangan & Solusi — Hambatan adopsi teknologi dan cara mengatasinya.'],
            ['time' => '19:00', 'text' => 'Penutup — Outlook UMKM digital ke depan.'],
        ],
    ],

];